name: py38dnn
channels:
  - defaults
  - conda-forge
  - anaconda
  - pytorch
  - plotly
dependencies:
  - absl-py==0.13.0
  - aiobotocore==2.1.0
  - aiohttp==3.8.1
  - aioitertools==0.7.1
  - aiosignal==1.2.0
  - argon2-cffi==20.1.0
  - arrow-cpp==3.0.0
  - astor==0.8.1
  - astunparse==1.6.3
  - async-timeout==4.0.1
  - async_generator==1.10
  - asyncpg==0.25.0
  - attrs==21.2.0
  - aws-c-common==0.4.57
  - aws-c-event-stream==0.1.6
  - aws-checksums==0.1.9
  - aws-sdk-cpp==1.8.130
  - babel==2.9.1
  - backcall==0.2.0
  - beautifulsoup4==4.10.0
  - blas==1.0
  - bleach==4.0.0
  - blinker==1.4
  - boost-cpp==1.73.0
  - boto3==1.20.24
  - botocore==1.23.24
  - bottleneck==1.3.2
  - brotli==1.0.9
  - brotlipy==0.7.0
  - bzip2==1.0.8
  - c-ares==1.17.1
  - ca-certificates==2022.4.26
  - cachetools==4.2.2
  - catalogue==2.0.6
  - certifi==2021.10.8
  - cffi==1.15.0
  - cfitsio==3.470
  - chardet==4.0.0
  - charset-normalizer==2.0.4
  - click==7.1.2
  - click-plugins==1.1.1
  - cligj==0.7.2
  - colorama==0.4.4
  - cron-descriptor==1.2.24
  - cryptography==3.4.8
  - cssselect==1.1.0
  - curl==7.55.1
  - cycler==0.11.0
  - cymem==2.0.5
  - cython-blis==0.7.4
  - dataclasses==0.8
  - debugpy==1.5.1
  - decorator==5.1.0
  - defusedxml==0.7.1
  - dill==0.3.4
  - emoji==1.6.1
  - entrypoints==0.3
  - et_xmlfile==1.1.0
  - expat==2.4.4
  - faker==8.8.1
  - fastrlock==0.8
  - feedfinder2==0.0.4
  - feedparser==6.0.8
  - filelock==3.4.0
  - fiona==1.8.21
  - flatbuffers==2.0.0
  - fonttools==4.25.0
  - freetype==2.10.4
  - freexl==1.0.6
  - frozenlist==1.2.0
  - fsspec==2022.1.0
  - gast==0.4.0
  - gdal==3.4.1
  - geoalchemy2==0.6.3
  - geographiclib==1.52
  - geopandas==0.9.0
  - geopandas-base==0.9.0
  - geopy==2.2.0
  - geos==3.8.0
  - geotiff==1.7.0
  - gflags==2.2.2
  - giflib==5.2.1
  - glog==0.4.0
  - google-api-core==1.25.1
  - google-auth==1.33.0
  - google-auth-oauthlib==0.4.4
  - google-cloud-core==1.7.1
  - google-cloud-storage==1.19.0
  - google-crc32c==1.1.2
  - google-pasta==0.2.0
  - google-resumable-media==1.3.1
  - googleapis-common-protos==1.53.0
  - greenlet==1.1.1
  - grpc-cpp==1.35.0
  - grpcio==1.42.0
  - h5py==3.6.0
  - hdf4==4.2.13
  - hdf5==1.10.6
  - icc_rt==2019.0.0
  - icu==68.1
  - idna==3.3
  - imageio==2.9.0
  - importlib-metadata==4.8.2
  - importlib_metadata==4.8.2
  - intel-openmp==2019.4
  - ipykernel==6.4.1
  - ipython==7.29.0
  - ipython_genutils==0.2.0
  - ipywidgets==7.6.5
  - jedi==0.18.0
  - jieba3k==0.35.1
  - jinja2==3.0.2
  - jmespath==0.10.0
  - joblib==1.1.0
  - jpeg==9d
  - jsonpickle==2.0.0
  - jsonschema==3.2.0
  - jupyter==1.0.0
  - jupyter_client==7.0.6
  - jupyter_console==6.4.0
  - jupyter_core==4.9.1
  - jupyterlab_pygments==0.1.2
  - jupyterlab_widgets==1.0.0
  - kealib==1.4.14
  - kiwisolver==1.3.1
  - krb5==1.19.3
  - langcodes==3.3.0
  - libboost==1.73.0
  - libclang==11.1.0
  - libcrc32c==1.1.1
  - libcurl==7.80.0
  - libevent==2.1.8
  - libgdal==3.4.1
  - libiconv==1.15
  - libmklml==2019.0.5
  - libnetcdf==4.8.1
  - libpng==1.6.37
  - libpq==12.9
  - libprotobuf==3.14.0
  - libspatialindex==1.9.3
  - libspatialite==4.3.0a
  - libssh2==1.9.0
  - libthrift==0.13.0
  - libtiff==4.2.0
  - libutf8proc==2.6.1
  - libuv==1.40.0
  - libwebp==1.2.0
  - libxml2==2.9.12
  - libxslt==1.1.34
  - libzip==1.8.0
  - lxml==4.6.3
  - lz4-c==1.9.3
  - m2w64-expat==2.1.1
  - m2w64-gcc-libgfortran==5.3.0
  - m2w64-gcc-libs==5.3.0
  - m2w64-gcc-libs-core==5.3.0
  - m2w64-gettext==0.19.7
  - m2w64-gmp==6.1.0
  - m2w64-libiconv==1.14
  - m2w64-libwinpthread-git==5.0.0.4634.697f757
  - m2w64-xz==5.2.2
  - mapclassify==2.4.3
  - markdown==3.3.4
  - markupsafe==2.0.1
  - matplotlib==3.5.0
  - matplotlib-base==3.5.0
  - matplotlib-inline==0.1.2
  - mido==1.2.10
  - missingno==0.4.2
  - mistune==0.8.4
  - mkl==2021.4.0
  - mkl-service==2.4.0
  - mkl_fft==1.3.1
  - mkl_random==1.2.2
  - more-itertools==8.12.0
  - msys2-conda-epoch==20160418
  - multidict==5.1.0
  - multiprocess==0.70.12.2
  - munch==2.5.0
  - munkres==1.1.4
  - murmurhash==1.0.5
  - music21==6.5.0
  - nb_conda_kernels==2.3.1
  - nbclient==0.5.3
  - nbconvert==6.1.0
  - nbformat==5.1.3
  - nest-asyncio==1.5.1
  - networkx==2.7.1
  - newspaper3k==0.2.8
  - ninja==1.10.2
  - ninja-base==1.10.2
  - nltk==3.6.5
  - notebook==6.4.6
  - numexpr==2.8.1
  - numpy==1.21.5
  - numpy-base==1.21.5
  - oauthlib==3.1.1
  - olefile==0.46
  - openjpeg==2.4.0
  - openpyxl==3.0.9
  - opensearch-py==1.0.0
  - openssl==1.1.1o
  - opt_einsum==3.3.0
  - packaging==21.3
  - pandas==1.3.4
  - pandocfilters==1.4.3
  - parso==0.8.2
  - pathy==0.6.0
  - patsy==0.5.2
  - pickleshare==0.7.5
  - pillow==8.4.0
  - pip==21.2.2
  - plotly==5.4.0
  - plotly_express==0.4.1
  - preshed==3.0.5
  - proj==6.2.1
  - prometheus_client==0.12.0
  - prompt-toolkit==3.0.20
  - prompt_toolkit==3.0.20
  - protobuf==3.14.0
  - psycopg2==2.8.5
  - pyasn1==0.4.8
  - pyasn1-modules==0.2.8
  - pycparser==2.21
  - pydantic==1.8.2
  - pydub==0.25.1
  - pygments==2.10.0
  - pyjwt==2.1.0
  - pyopenssl==21.0.0
  - pyparsing==3.0.4
  - pyproj==2.6.1.post1
  - pyqt==5.12.3
  - pyqt-impl==5.12.3
  - pyqt5-sip==4.19.18
  - pyqtchart==5.12
  - pyqtwebengine==5.12.1
  - pyreadline==2.1
  - pyrsistent==0.18.0
  - pysocks==1.7.1
  - python==3.8.12
  - python-dateutil==2.8.2
  - python-flatbuffers==1.12
  - python-xxhash==2.0.2
  - python_abi==3.8
  - pytz==2021.3
  - pywin32==228
  - pywinpty==0.5.7
  - pyyaml==6.0
  - pyzmq==22.3.0
  - qt==5.12.9
  - qtconsole==5.1.1
  - qtpy==1.10.0
  - re2==2020.11.01
  - regex==2021.8.3
  - requests==2.26.0
  - requests-aws4auth==1.1.1
  - requests-file==1.5.1
  - requests-oauthlib==1.3.0
  - rsa==4.7.2
  - rtree==0.9.7
  - s3fs==2022.1.0
  - s3transfer==0.5.0
  - sacremoses==0.0.43
  - scikit-learn==1.0.1
  - scipy==1.7.3
  - seaborn==0.11.2
  - send2trash==1.8.0
  - setuptools==58.0.4
  - sgmllib3k==1.0.0
  - shapely==1.7.1
  - shellingham==1.3.1
  - sip==4.19.13
  - six==1.16.0
  - smart_open==5.1.0
  - snappy==1.1.8
  - soupsieve==2.3.1
  - sqlalchemy==1.4.27
  - sqlite==3.38.2
  - statsmodels==0.13.0
  - tabulate==0.8.9
  - tbb==2021.5.0
  - tenacity==8.0.1
  - termcolor==1.1.0
  - terminado==0.9.4
  - testpath==0.5.0
  - text-unidecode==1.3
  - threadpoolctl==2.2.0
  - tiledb==2.2.9
  - tinysegmenter==0.3
  - tk==8.6.11
  - tldextract==3.1.2
  - tornado==6.1
  - tqdm==4.62.3
  - traitlets==5.1.1
  - typer==0.4.0
  - typing-extensions==3.10.0.2
  - typing_extensions==3.10.0.2
  - unidecode==1.2.0
  - urllib3==1.26.7
  - vc==14.2
  - vs2015_runtime==14.27.29016
  - wasabi==0.8.2
  - wcwidth==0.2.5
  - webcolors==1.11.1
  - webencodings==0.5.1
  - werkzeug==2.0.2
  - wheel==0.35.1
  - widgetsnbextension==3.5.1
  - win_inet_pton==1.1.0
  - wincertstore==0.2
  - winpty==0.4.3
  - wordcloud==1.8.1
  - wrapt==1.13.3
  - xerces-c==3.2.3
  - xlrd==2.0.1
  - xxhash==0.8.0
  - xz==5.2.5
  - yaml==0.2.5
  - yarl==1.6.3
  - zipp==3.6.0
  - zlib==1.2.11
  - zstd==1.4.9
  - pip:
    - aiofiles==0.8.0
    - h11==0.13.0
    - peewee==3.14.9
    - plac==1.1.3
    - retrie==0.1.2
    - starlette==0.14.2
    - toolz==0.11.2
    - uvicorn==0.13.4